'use client';
import {useEffect,useState} from 'react';
import type {CSSProperties} from 'react';
import styles from '../platform-pages.module.css';
import AddressAutocomplete from '../components/address-autocomplete';
import {googleMapsDirections,displayBusinessAddress} from '../../lib/maps';
import {themeStyles} from '../../server/themes.mjs';
import {US_STATES,canonicalState} from '../../lib/business-options';
type Theme={palette:string;bodyFont:string;headingFont:string;colors:Record<string,string>};
type Profile={id:string;slug:string;name:string;industry:string;description:string;city:string;region:string;address?:string;brand_primary:string;brand_background:string;theme?:Theme;is_listed:boolean;listing_requested:boolean;plan_code:string;ai_addon:boolean;planBenefits?:{name:string;bookableStaff:number;limits:{services:number;bookingFields:number;sessionSeries:number;membershipPlans:number}}};
export default function BusinessProfile(){
 const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[address,setAddress]=useState(''),[city,setCity]=useState(''),[region,setRegion]=useState(''),[error,setError]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/business',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);if(!d.business)throw Error('No business has been created for this account.');setProfile(d.business);setName(d.business.name);setDescription(d.business.description);setAddress(/^Add your /i.test(d.business.address||'')?'':d.business.address||'');setCity(d.business.city);setRegion(d.business.region);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function save(requestListing:boolean){setBusy(true);setError('');setMsg('');try{const r=await fetch('/api/business',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description,address,city,region,requestListing})});const d=await r.json();if(!r.ok)throw Error(d.error);setMsg(requestListing?'Listing requested. Awaiting platform review.':'Business profile and address saved.');await load();window.dispatchEvent(new Event('selahflow:business-updated'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const theme=profile?themeStyles(profile.theme,profile.brand_primary,profile.brand_background) as CSSProperties:undefined;
 const location=displayBusinessAddress(address,city,region);
 return <main className={styles.shell+' '+(profile?styles.businessTheme:'')} style={theme}><header className={styles.top}><a href="/" className={styles.brand}><img className="selah-logo" src="/brand/logo.svg" alt="SelahFlow" width="380" height="68"/> / Business Profile</a><nav className={styles.nav}><a href={profile?"/studio/"+profile.slug:"/login"}>Owner Dashboard</a><a href="/pricing">Plans</a><a href="/discover">Marketplace</a></nav></header><section className={styles.hero}><h1>Business profile</h1><p>Configure how customers see your business and request inclusion in the discovery marketplace.</p></section>{error&&<p className={styles.alert} role="alert">{error}</p>}{msg&&<p className={styles.success} role="status">{msg}</p>}{!profile?<p>Loading profile… <a href="/login">Sign in</a></p>:<section className={styles.card} style={{maxWidth:720}}><p>Owner dashboard: <a href={'/studio/'+profile.slug}>/studio/{profile.slug}</a></p><p>Public business page: <a href={'/'+profile.slug}>/{profile.slug}</a></p><p>Customer booking: <a href={'/book/'+profile.slug}>/book/{profile.slug}</a></p><p>Current plan: <strong>{profile.planBenefits?.name||profile.plan_code}</strong> · Up to {profile.planBenefits?.bookableStaff||1} team members, {profile.planBenefits?.limits.services||10} services, {profile.planBenefits?.limits.bookingFields||5} booking questions, {profile.planBenefits?.limits.sessionSeries||15} session templates and {profile.planBenefits?.limits.membershipPlans||2} active membership offers. <a href="/pricing">Compare benefits</a>. Paid checkout is not connected; verified changes can be applied by a platform administrator.</p><p>Marketplace status: <strong>{profile.is_listed?'Publicly listed':profile.listing_requested?'Awaiting approval':'Not listed'}</strong></p><label>Business name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={600} rows={4}/></label>
 <AddressAutocomplete label="Street address" value={address} onChange={setAddress} onSelect={item=>{setAddress(item.label);setCity(item.city);setRegion(canonicalState(item.region)||'');}}/>
 {location&&<p><a className="sf-directions-link" href={googleMapsDirections(location)} target="_blank" rel="noopener noreferrer">Get Google Maps directions to your business ↗</a></p>}
 <label>City<input value={city} onChange={e=>setCity(e.target.value)} maxLength={80}/></label><label>U.S. state<select value={canonicalState(region)} onChange={e=>setRegion(e.target.value)}><option value="">Select state</option>{US_STATES.map(([code,label])=><option key={code} value={label}>{label}</option>)}</select></label><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:22}}><button className={styles.button} disabled={busy} onClick={()=>save(false)}>Save changes</button><button className={styles.secondary} disabled={busy||profile.is_listed||profile.listing_requested} onClick={()=>save(true)}>Request marketplace listing</button></div><p><small>Address search powered by OpenStreetMap. You can enter addresses manually. Business profiles inherit the same colors and fonts as your booking page. Listings require approval.</small></p></section>}</main>;
}
